modLoader = "javafml"
loaderVersion = "[46,)"
license = "All rights reserved"

[[mods]]
modId = "gongdaobei"
version = "${file.jarVersion}"
displayName = "Gongdaobei: Service discovery and registration"
authors = "TeaConMC"
description = '''
Gongdaobei: Service discovery and registration
'''

[[dependencies.gongdaobei]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gongdaobei]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
